apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-tsxx
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rorai-tenant/devfile-sample/devfile-sample-tsxx@sha256:5855a923956774af14a909ebf96b73284eae8ddbaade4e0aa58a97d0749f6d8d
        name: my-nodejs
        resources: {}
status: {}
